ALTER TABLE `fingerprint2` 
ADD COLUMN `ip` VARCHAR(32) NULL AFTER `fp`
CHANGE COLUMN `userAgent` `userAgent` VARCHAR(100) NULL DEFAULT null COMMENT '使用者代理' ,
CHANGE COLUMN `webdriver` `webdriver` VARCHAR(50) NULL DEFAULT null COMMENT 'webdriver' ,
CHANGE COLUMN `language` `language` VARCHAR(30) NULL DEFAULT null COMMENT '語言' ,
CHANGE COLUMN `colorDepth` `colorDepth` INT(11) NULL DEFAULT null COMMENT '顏色深度' ,
CHANGE COLUMN `deviceMemory` `deviceMemory` INT(11) NULL DEFAULT null COMMENT '裝置記憶體' ,
CHANGE COLUMN `pixelRatio` `pixelRatio` INT(11) NULL DEFAULT null COMMENT '像素比率' ,
CHANGE COLUMN `hardwareConcurrency` `hardwareConcurrency` INT(11) NULL DEFAULT null COMMENT '硬體同時執行' ,
CHANGE COLUMN `screenResolution` `screenResolution` VARCHAR(1000) NULL DEFAULT null COMMENT '螢幕解析度' ,
CHANGE COLUMN `availableScreenResolution` `availableScreenResolution` VARCHAR(1000) NULL DEFAULT null COMMENT '允許的螢幕解析度' ,
CHANGE COLUMN `timezoneOffset` `timezoneOffset` INT(11) NULL DEFAULT null COMMENT '時區偏移' ,
CHANGE COLUMN `timezone` `timezone` VARCHAR(50) NULL DEFAULT null COMMENT '時區' ,
CHANGE COLUMN `sessionStorage` `sessionStorage` TINYINT(1) NULL DEFAULT null COMMENT 'session儲存' ,
CHANGE COLUMN `localStorage` `localStorage` TINYINT(1) NULL DEFAULT null COMMENT 'local儲存' ,
CHANGE COLUMN `indexedDb` `indexedDb` TINYINT(1) NULL DEFAULT null COMMENT '索引的資料庫' ,
CHANGE COLUMN `addBehavior` `addBehavior` TINYINT(1) NULL DEFAULT null COMMENT '新增行為' ,
CHANGE COLUMN `openDatabase` `openDatabase` TINYINT(1) NULL DEFAULT null COMMENT '開啟資料庫' ,
CHANGE COLUMN `cpuClass` `cpuClass` VARCHAR(100) NULL DEFAULT null COMMENT 'CPU等級' ,
CHANGE COLUMN `platform` `platform` VARCHAR(50) NULL DEFAULT null COMMENT '平台' ,
CHANGE COLUMN `doNotTrack` `doNotTrack` VARCHAR(100) NULL DEFAULT null ,
CHANGE COLUMN `plugins` `plugins` VARCHAR(5000) NULL DEFAULT null COMMENT '外掛' ,
CHANGE COLUMN `canvas` `canvas` VARCHAR(5000) NULL DEFAULT null COMMENT 'canvas' ,
CHANGE COLUMN `webgl` `webgl` VARCHAR(5000) NULL DEFAULT null COMMENT 'webgl' ,
CHANGE COLUMN `webglVendorAndRenderer` `webglVendorAndRenderer` VARCHAR(200) NULL DEFAULT null COMMENT 'webgl庫&渲染器' ,
CHANGE COLUMN `adBlock` `adBlock` TINYINT(1) NULL DEFAULT null COMMENT '廣告阻擋器' ,
CHANGE COLUMN `hasLiedLanguages` `hasLiedLanguages` TINYINT(1) NULL DEFAULT null ,
CHANGE COLUMN `hasLiedResolution` `hasLiedResolution` TINYINT(1) NULL DEFAULT null ,
CHANGE COLUMN `hasLiedOs` `hasLiedOs` TINYINT(1) NULL DEFAULT null ,
CHANGE COLUMN `hasLiedBrowser` `hasLiedBrowser` TINYINT(1) NULL DEFAULT null ,
CHANGE COLUMN `touchSupport` `touchSupport` VARCHAR(300) NULL DEFAULT null COMMENT '觸控支援' ,
CHANGE COLUMN `fonts` `fonts` VARCHAR(1500) NULL DEFAULT null COMMENT '字體' ,
CHANGE COLUMN `fontsFlash` `fontsFlash` VARCHAR(100) NULL DEFAULT null COMMENT '字體快閃' ,
CHANGE COLUMN `audio` `audio` FLOAT NULL DEFAULT null COMMENT '音頻' ,
CHANGE COLUMN `enumerateDevices` `enumerateDevices` VARCHAR(100) NULL DEFAULT null COMMENT '列舉設備' ;
